import Head from "next/head";
import { useForm } from "react-hook-form";
import "keen-slider/keen-slider.min.css";
import { addClothing } from "../../../services/addClothes";
import Tags from "../../../components/painel/tags";
import { FormControl, InputLabel, Select, MenuItem, SelectChangeEvent, TextField } from "@mui/material";
import { useState } from "react";
import { setCurrencyFormat, currencyUnformat } from "../../../utils";

type typeClothing = {
  Name: string;
  Tag: string;
  Price: number;
  ImageUrl: string;
  Size: "M" | "P" | "G";
  amount: number;
};

export default function AddProductsForm() {
  const [Size, setSize] = useState("");
  const [priceError, setPriceError] = useState<boolean>(false);
  const {
    register,
    handleSubmit,
    setValue,
    formState: { errors },
  } = useForm();
  const onSubmit = (data) => {
    console.log(data);

    addClothing(data);
  };

  const [currency, setCurrency] = useState<string>();

  const handleChange = (event: SelectChangeEvent) => {
    setValue("Size", event.target.value as string);
    setSize(event.target.value as string);
  };
  return (
    <div className="bg-slate-400 h-full">
      <Head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col justify-center ">
        <form onSubmit={handleSubmit(onSubmit)} className="bg-white shadow-md rounded flex flex-col gap-2 px-8 pt-6 pb-8 m-4 ">
          <h2 className="text-center">Adicinar Produto</h2>
          <div className="mb-2">
            <TextField id="outlined-basic" label="Titulo" variant="outlined" {...register("Name", { required: true })} sx={{ width: "100%" }} />
          </div>
          <div className="mb-2">
            <Tags setValue={setValue} />
          </div>
          <div className="mb-2">
            <TextField
              id="outlined-basic"
              label="Preço"
              variant="outlined"
              required
              error={priceError ? true : false}
              value={currency}
              onChange={(event: React.ChangeEvent<HTMLInputElement>) => {
                console.log(currencyUnformat(setCurrencyFormat(event.target.value)));
                setCurrency(setCurrencyFormat(event.target.value));
                setValue("Price", currencyUnformat(event.target.value));
              }}
              sx={{ width: "100%" }}
            />
          </div>
          <div className="mb-2">
            <TextField id="outlined-basic" label="Link da Imagem" variant="outlined" {...register("ImageUrl", { required: true })} sx={{ width: "100%" }} />
          </div>
          <div className="mb-2">
            <FormControl fullWidth>
              <InputLabel id="demo-simple-select-label">Tamanho</InputLabel>
              <Select labelId="demo-simple-select-label" id="demo-simple-select" value={Size} label="Tamanho" onChange={handleChange}>
                <MenuItem value={"P"}>P</MenuItem>
                <MenuItem value={"M"}>M</MenuItem>
                <MenuItem value={"G"}>G</MenuItem>
              </Select>
            </FormControl>
          </div>
          <div className="mb-2">
            <TextField type="number" id="outlined-basic" label="Quantidade" variant="outlined" {...register("Amount", { required: true })} sx={{ width: "100%" }} />
          </div>
          <div className="flex items-center justify-between">
            <button className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
              adicionar
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
