import Head from "next/head";

import "keen-slider/keen-slider.min.css";

import styles from "../styles/Home.module.css";
import Entry from "../components/home/Entry";
import BasicLayout from "../components/misc";
import Products from "../components/products/products";
import { ListTeam } from "../components/home/ListTeam";
import { Base } from "../components/home/Base";

export default function Home() {
  return (
    <div>
      <Head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BasicLayout>
        <Entry />

        <div className="flex flex-col">
          <ListTeam />
          <Products />
          <Base />
        </div>
      </BasicLayout>
    </div>
  );
}
