import Head from "next/head";

import "keen-slider/keen-slider.min.css";
export default function ControlPanel() {
  return (
    <div>
      <Head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col">Painel de controle</div>
    </div>
  );
}
